services:
  p1:
    tty: true
    image: ros2_humble_yasmin
    build: .
    container_name: ros2_cognitiva_p1_container
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.xauth_docker/share/:/tmp/xauth/
      - /dev/input:/dev/input
      - /dev/bus/usb:/dev/bus/usb
      - ../P1:/home/user/ros2_ws:rw
      - ./scripts:/scripts
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth
      - LIBGL_ALWAYS_SOFTWARE=1
      - SVGA_VGPU10=0
      - GALLIUM_DRIVER=llvmpipe
    working_dir: /home/user/ros2_ws
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb:rw
    user: "user:user"
    command: ["/bin/bash", "-c", "chmod +x /scripts/setup_bashrc.sh && /scripts/setup_bashrc.sh && bash"]

  p2:
    tty: true
    image: ros2_humble_yasmin
    build: .
    container_name: ros2_cognitiva_p2_container
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.xauth_docker/share/:/tmp/xauth/
      - /dev/input:/dev/input
      - /dev/bus/usb:/dev/bus/usb
      - ../P2:/home/user/ros2_ws:rw
      - ./scripts:/scripts
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth
      - LIBGL_ALWAYS_SOFTWARE=1
      - SVGA_VGPU10=0
      - GALLIUM_DRIVER=llvmpipe
    working_dir: /home/user/ros2_ws
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb:rw
    user: "user:user"
    command: ["/bin/bash", "-c", "chmod +x /scripts/setup_bashrc.sh && /scripts/setup_bashrc.sh && bash"]
