(define (problem robot_problem)
		(:domain actionplanner4pathgenerator)
	(:objects kitchen livingroom bedroom toilet corridor gym )
	(:init (location kitchen)
		(location livingroom)
		(location bedroom)
		(location corridor)
		(location toilet)
		(location gym)
		(connect kitchen corridor)
		(connect livingroom corridor)
		(connect livingroom gym)
		(connect bedroom corridor)
		(connect bedroom toilet)
		(at robot kitchen)
	)
	(:goal (at robot toilet))
)